/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Auth Config
         * @description Unauthenticated: tell the frontend whether Google SSO is required.
         */
        get: operations["get_auth_config_api_auth_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/datasets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Datasets
         * @description List dataset names that have an ``output.db``.
         */
        get: operations["list_datasets_api_datasets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/datasets/{dataset}/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Conversations
         * @description Return one row per conversation/user for the review queue.
         *
         *     Groups ``run_segment`` rows by conversation (segment count, distinct
         *     topics), counts messages via the dataset adapter, and folds in review
         *     state from gold.db.
         */
        get: operations["list_conversations_api_datasets__dataset__conversations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/datasets/{dataset}/conversations/{conversation}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Conversation
         * @description Return a conversation's messages plus all its segments (boundary view).
         */
        get: operations["get_conversation_api_datasets__dataset__conversations__conversation__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/datasets/{dataset}/conversations/{conversation}/boundaries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Replace Boundaries
         * @description REPLACE all gold_segments for a conversation with the posted spans.
         *
         *     Each new gold span inherits topic/subtopic/sentiment from the overlapping
         *     predicted segment when the client leaves them unset, so split children keep
         *     the parent's label and a merge takes the primary overlapped segment's label.
         */
        post: operations["replace_boundaries_api_datasets__dataset__conversations__conversation__boundaries_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/datasets/{dataset}/segments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Segments
         * @description Return the review queue: run_segment rows joined with gold review state.
         *
         *     Filters (all optional): ``status`` (``reviewed``/``unreviewed``), ``topic``
         *     exact match, ``max_confidence`` (keep segments at or below that confidence).
         */
        get: operations["list_segments_api_datasets__dataset__segments_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/datasets/{dataset}/segments/{segment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Segment
         * @description Return a segment with its conversation messages, span, and siblings.
         */
        get: operations["get_segment_api_datasets__dataset__segments__segment_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/datasets/{dataset}/segments/{segment_id}/annotate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Annotate Segment
         * @description Write a gold_segment mirroring the base span with corrected labels.
         */
        post: operations["annotate_segment_api_datasets__dataset__segments__segment_id__annotate_post"];
        /**
         * Clear Segment Annotation
         * @description Clear a segment's gold annotation, reverting it to unannotated.
         *
         *     Deletes the segment's relabel/confirm gold_segment row(s) + its review_state
         *     entry so undoing a first annotation reverts the segment to unreviewed.
         */
        delete: operations["clear_segment_annotation_api_datasets__dataset__segments__segment_id__annotate_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/datasets/{dataset}/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Stats
         * @description Return review progress: totals and per-topic counts on the effective set.
         */
        get: operations["get_stats_api_datasets__dataset__stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/datasets/{dataset}/taxonomy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Taxonomy
         * @description Return the dataset's user taxonomy from the metadata provider.
         */
        get: operations["get_taxonomy_api_datasets__dataset__taxonomy_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AnnotateRequest
         * @description Relabel/confirm one base segment's topic/subtopic.
         */
        AnnotateRequest: {
            /** Reviewed By */
            reviewed_by?: string | null;
            /** Sentiment */
            sentiment?: string | null;
            /** True Subtopic */
            true_subtopic: string;
            /** True Topic */
            true_topic: string;
        };
        /**
         * AnnotateResponse
         * @description Result of an annotate write.
         */
        AnnotateResponse: {
            /** Gold Segment Id */
            gold_segment_id: number;
            /**
             * Reviewed
             * @default true
             */
            reviewed: boolean;
        };
        /**
         * AuthConfig
         * @description Whether Google SSO is required (unauthenticated config endpoint).
         */
        AuthConfig: {
            /** Sso Enabled */
            sso_enabled: boolean;
        };
        /**
         * BoundaryRequest
         * @description Replace a conversation's gold spans (split/merge).
         */
        BoundaryRequest: {
            /** Reviewed By */
            reviewed_by?: string | null;
            /** Segments */
            segments: components["schemas"]["BoundarySpan"][];
        };
        /**
         * BoundaryResponse
         * @description Result of a boundary replace.
         */
        BoundaryResponse: {
            /** Conversation */
            conversation: string;
            /** Gold Segments Written */
            gold_segments_written: number;
        };
        /**
         * BoundarySpan
         * @description One corrected gold span in a boundary edit.
         */
        BoundarySpan: {
            /** Message Indices */
            message_indices: number[];
            /** Sentiment */
            sentiment?: string | null;
            /** Subtopic */
            subtopic?: string | null;
            /** Topic */
            topic?: string | null;
        };
        /**
         * ClearAnnotationResponse
         * @description Result of clearing a segment's gold annotation.
         */
        ClearAnnotationResponse: {
            /** Deleted */
            deleted: number;
            /**
             * Reviewed
             * @default false
             */
            reviewed: boolean;
            /** Segment Id */
            segment_id: number;
        };
        /**
         * ConversationSummary
         * @description One row in the user/conversation review queue.
         */
        ConversationSummary: {
            /** Conversation */
            conversation: string;
            /** Message Count */
            message_count: number;
            /**
             * Reviewed
             * @default false
             */
            reviewed: boolean;
            /** Reviewed Count */
            reviewed_count: number;
            /** Segment Count */
            segment_count: number;
            /** Topics */
            topics?: string[];
        };
        /**
         * ConversationView
         * @description All messages + all machine segments for the boundary-edit view.
         */
        ConversationView: {
            /** Conversation */
            conversation: string;
            /** Gold Segments */
            gold_segments: components["schemas"]["GoldSegment"][];
            /** Messages */
            messages: components["schemas"]["Message"][];
            /** Segments */
            segments: components["schemas"]["SegmentSummary"][];
        };
        /**
         * GoldSegment
         * @description A persisted human-gold segment.
         */
        GoldSegment: {
            /** Base Segment Id */
            base_segment_id?: number | null;
            /** Conversation */
            conversation: string;
            /** Id */
            id: number;
            /** Message Indices */
            message_indices: number[];
            /** Reviewed At */
            reviewed_at?: string | null;
            /** Reviewed By */
            reviewed_by?: string | null;
            /** Sentiment */
            sentiment?: string | null;
            /** Source */
            source?: string | null;
            /** Subtopic */
            subtopic?: string | null;
            /** Topic */
            topic?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * Message
         * @description One normalized conversation message, with its positional index.
         */
        Message: {
            /** Createdat */
            createdAt?: string | null;
            /** Id */
            id: string;
            /** Index */
            index: number;
            /** Message */
            message: string;
            /** Type */
            type: string;
        };
        /**
         * SegmentDetail
         * @description A segment plus its conversation context for the annotation panel.
         */
        SegmentDetail: {
            /** Messages */
            messages: components["schemas"]["Message"][];
            segment: components["schemas"]["SegmentSummary"];
            /** Siblings */
            siblings: components["schemas"]["SegmentSummary"][];
            /** Span */
            span: components["schemas"]["Message"][];
        };
        /**
         * SegmentSummary
         * @description A machine segment as listed in the review queue.
         */
        SegmentSummary: {
            /** Chunk Index */
            chunk_index: number;
            /** Conversation */
            conversation: string;
            /** Id */
            id: number;
            /** Label Confidence */
            label_confidence?: number | null;
            /** Message Indices */
            message_indices: number[];
            /**
             * Reviewed
             * @default false
             */
            reviewed: boolean;
            /** Sentiment */
            sentiment?: string | null;
            /** Subtopic */
            subtopic?: string | null;
            /** Summary */
            summary?: string | null;
            /** Topic */
            topic?: string | null;
            /** True Subtopic */
            true_subtopic?: string | null;
            /** True Topic */
            true_topic?: string | null;
        };
        /**
         * Stats
         * @description Review progress for a dataset.
         */
        Stats: {
            /** Per Topic */
            per_topic?: {
                [key: string]: number;
            };
            /** Reviewed */
            reviewed: number;
            /** Total */
            total: number;
            /** Unreviewed */
            unreviewed: number;
        };
        /**
         * TaxonomyEntry
         * @description One taxonomy (topic, subtopic) row from the metadata provider.
         */
        TaxonomyEntry: {
            /** Description */
            description?: string | null;
            /** Subtopic */
            subtopic?: string | null;
            /** Topic */
            topic?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_auth_config_api_auth_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthConfig"];
                };
            };
        };
    };
    list_datasets_api_datasets_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_conversations_api_datasets__dataset__conversations_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                dataset: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_conversation_api_datasets__dataset__conversations__conversation__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                dataset: string;
                conversation: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    replace_boundaries_api_datasets__dataset__conversations__conversation__boundaries_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                dataset: string;
                conversation: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BoundaryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoundaryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_segments_api_datasets__dataset__segments_get: {
        parameters: {
            query?: {
                status?: string | null;
                topic?: string | null;
                max_confidence?: number | null;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                dataset: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SegmentSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_segment_api_datasets__dataset__segments__segment_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                dataset: string;
                segment_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SegmentDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    annotate_segment_api_datasets__dataset__segments__segment_id__annotate_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                dataset: string;
                segment_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnnotateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnnotateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clear_segment_annotation_api_datasets__dataset__segments__segment_id__annotate_delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                dataset: string;
                segment_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClearAnnotationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_stats_api_datasets__dataset__stats_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                dataset: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Stats"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_taxonomy_api_datasets__dataset__taxonomy_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                dataset: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaxonomyEntry"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
