/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Auth Config
         * @description Unauthenticated: tell the frontend whether Google SSO is required.
         */
        get: operations["get_auth_config_api_auth_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/datasets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Datasets
         * @description List registered dataset names.
         */
        get: operations["list_datasets_api_datasets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/datasets/{dataset}/bertopic-labels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Bertopic Labels
         * @description Return distinct BERTopic topics + subtopics with per-conversation counts.
         */
        get: operations["get_bertopic_labels_api_datasets__dataset__bertopic_labels_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/datasets/{dataset}/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Conversations
         * @description Return a PAGINATED, searchable page of conversation summaries.
         *
         *     ``q`` matches conversation ext_id OR message content. ``status``/``topic``
         *     filter on the effective segmentation. ``labeler`` restricts the page to that
         *     labeler's worklist assignments. ``bertopic_topic``/``bertopic_subtopic``
         *     restrict to conversations with a gold segment carrying that BERTopic label.
         *     ``mismatch`` restricts to conversations with a reviewed gold segment whose
         *     human label disagrees with its BERTopic source label. Shape:
         *     ``{items,total,page,page_size}``.
         */
        get: operations["list_conversations_api_datasets__dataset__conversations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/datasets/{dataset}/conversations/{conversation}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Conversation
         * @description Return a conversation's messages plus its effective + gold segments.
         */
        get: operations["get_conversation_api_datasets__dataset__conversations__conversation__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/datasets/{dataset}/conversations/{conversation}/boundaries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Replace Boundaries
         * @description REPLACE all gold for a conversation with the posted spans (split/merge).
         *
         *     Each new span inherits topic/subtopic/sentiment from the overlapping
         *     predicted segment when the client leaves them unset.
         */
        post: operations["replace_boundaries_api_datasets__dataset__conversations__conversation__boundaries_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/datasets/{dataset}/labelers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Labelers
         * @description Return the distinct worklist labelers for the dataset, sorted (may be empty).
         */
        get: operations["get_labelers_api_datasets__dataset__labelers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/datasets/{dataset}/segments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Segments
         * @description Return the predicted-segment review queue with gold review state.
         *
         *     Filters (optional): ``status`` (``reviewed``/``unreviewed``), ``topic`` exact
         *     match, ``max_confidence`` (keep segments at or below that confidence).
         */
        get: operations["list_segments_api_datasets__dataset__segments_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/datasets/{dataset}/segments/{segment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Segment
         * @description Return a segment with its conversation messages, span, and siblings.
         */
        get: operations["get_segment_api_datasets__dataset__segments__segment_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/datasets/{dataset}/segments/{segment_id}/annotate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Annotate Segment
         * @description Write a relabel/confirm gold mirroring the predicted span with new labels.
         */
        post: operations["annotate_segment_api_datasets__dataset__segments__segment_id__annotate_post"];
        /**
         * Clear Segment Annotation
         * @description Clear a segment's relabel/confirm gold, reverting it to unannotated.
         */
        delete: operations["clear_segment_annotation_api_datasets__dataset__segments__segment_id__annotate_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/datasets/{dataset}/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Stats
         * @description Return review progress: totals and per-topic counts on the effective set.
         */
        get: operations["get_stats_api_datasets__dataset__stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/datasets/{dataset}/taxonomy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Taxonomy
         * @description Return the dataset's user taxonomy.
         */
        get: operations["get_taxonomy_api_datasets__dataset__taxonomy_get"];
        put?: never;
        /**
         * Create Taxonomy
         * @description Add a taxonomy option (idempotent: a duplicate create is a no-op).
         */
        post: operations["create_taxonomy_api_datasets__dataset__taxonomy_post"];
        /**
         * Delete Taxonomy
         * @description Remove a taxonomy option. Already-applied segment labels are left intact.
         */
        delete: operations["delete_taxonomy_api_datasets__dataset__taxonomy_delete"];
        options?: never;
        head?: never;
        /**
         * Rename Taxonomy
         * @description Rename a taxonomy option, cascading the rename to applied segment labels.
         */
        patch: operations["rename_taxonomy_api_datasets__dataset__taxonomy_patch"];
        trace?: never;
    };
    "/api/datasets/{dataset}/taxonomy/merge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Merge Taxonomy
         * @description Fold one topic into another: cascade labels then drop the duplicate rows.
         */
        post: operations["merge_taxonomy_api_datasets__dataset__taxonomy_merge_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/datasets/{dataset}/used-topics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Used Topics
         * @description Return distinct topic names already used for the dataset, frequent first.
         */
        get: operations["get_used_topics_api_datasets__dataset__used_topics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AnnotateRequest
         * @description Relabel/confirm one base segment's topic/subtopic.
         */
        AnnotateRequest: {
            /** Reviewed By */
            reviewed_by?: string | null;
            /** Sentiment */
            sentiment?: string | null;
            /** True Subtopic */
            true_subtopic: string;
            /** True Topic */
            true_topic: string;
        };
        /**
         * AnnotateResponse
         * @description Result of an annotate write.
         */
        AnnotateResponse: {
            /** Gold Segment Id */
            gold_segment_id: number;
            /**
             * Reviewed
             * @default true
             */
            reviewed: boolean;
        };
        /**
         * AuthConfig
         * @description Whether Google SSO is required (unauthenticated config endpoint).
         */
        AuthConfig: {
            /** Sso Enabled */
            sso_enabled: boolean;
        };
        /**
         * BertopicLabels
         * @description Distinct BERTopic topics + subtopics (with parent topic) and counts.
         */
        BertopicLabels: {
            /** Subtopics */
            subtopics?: components["schemas"]["BertopicSubtopicCount"][];
            /** Topics */
            topics?: components["schemas"]["BertopicTopicCount"][];
        };
        /**
         * BertopicSubtopicCount
         * @description A distinct BERTopic subtopic with its parent topic and per-conversation count.
         */
        BertopicSubtopicCount: {
            /** Count */
            count: number;
            /** Subtopic */
            subtopic: string;
            /** Topic */
            topic?: string | null;
        };
        /**
         * BertopicTopicCount
         * @description A distinct BERTopic topic with its per-conversation count.
         */
        BertopicTopicCount: {
            /** Count */
            count: number;
            /** Topic */
            topic: string;
        };
        /**
         * BoundaryRequest
         * @description Replace a conversation's gold spans (split/merge).
         */
        BoundaryRequest: {
            /** Reviewed By */
            reviewed_by?: string | null;
            /** Segments */
            segments: components["schemas"]["BoundarySpan"][];
        };
        /**
         * BoundaryResponse
         * @description Result of a boundary replace.
         */
        BoundaryResponse: {
            /** Conversation */
            conversation: string;
            /** Gold Segments Written */
            gold_segments_written: number;
        };
        /**
         * BoundarySpan
         * @description One corrected gold span in a boundary edit.
         */
        BoundarySpan: {
            /** Message Indices */
            message_indices: number[];
            /** Sentiment */
            sentiment?: string | null;
            /** Subtopic */
            subtopic?: string | null;
            /** Topic */
            topic?: string | null;
        };
        /**
         * ClearAnnotationResponse
         * @description Result of clearing a segment's gold annotation.
         */
        ClearAnnotationResponse: {
            /** Deleted */
            deleted: number;
            /**
             * Reviewed
             * @default false
             */
            reviewed: boolean;
            /** Segment Id */
            segment_id: number;
        };
        /**
         * ConversationPage
         * @description A paginated page of conversation summaries for the review queue.
         */
        ConversationPage: {
            /** Items */
            items?: components["schemas"]["ConversationSummary"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
        };
        /**
         * ConversationSummary
         * @description One row in the user/conversation review queue.
         */
        ConversationSummary: {
            /** Conversation */
            conversation: string;
            /** Message Count */
            message_count: number;
            /**
             * Reviewed
             * @default false
             */
            reviewed: boolean;
            /** Reviewed Count */
            reviewed_count: number;
            /** Segment Count */
            segment_count: number;
            /** Topics */
            topics?: string[];
        };
        /**
         * ConversationView
         * @description All messages + all machine segments for the boundary-edit view.
         */
        ConversationView: {
            /** Conversation */
            conversation: string;
            /**
             * Frozen Boundaries
             * @default false
             */
            frozen_boundaries: boolean;
            /** Gold Segments */
            gold_segments: components["schemas"]["GoldSegment"][];
            /** Messages */
            messages: components["schemas"]["Message"][];
            /** Segments */
            segments: components["schemas"]["SegmentSummary"][];
        };
        /**
         * GoldSegment
         * @description A persisted human-gold segment.
         */
        GoldSegment: {
            /** Base Segment Id */
            base_segment_id?: number | null;
            /** Conversation */
            conversation: string;
            /** Id */
            id: number;
            /** Message Indices */
            message_indices: number[];
            /** Reviewed At */
            reviewed_at?: string | null;
            /** Reviewed By */
            reviewed_by?: string | null;
            /** Sentiment */
            sentiment?: string | null;
            /** Source */
            source?: string | null;
            /** Subtopic */
            subtopic?: string | null;
            /** Topic */
            topic?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * Labelers
         * @description Distinct worklist labelers for a dataset, sorted (may be empty).
         */
        Labelers: {
            /** Labelers */
            labelers?: string[];
        };
        /**
         * Message
         * @description One normalized conversation message, with its positional index.
         */
        Message: {
            /** Createdat */
            createdAt?: string | null;
            /** Id */
            id: string;
            /** Index */
            index: number;
            /** Message */
            message: string;
            /** Type */
            type: string;
        };
        /**
         * SegmentDetail
         * @description A segment plus its conversation context for the annotation panel.
         */
        SegmentDetail: {
            /** Messages */
            messages: components["schemas"]["Message"][];
            segment: components["schemas"]["SegmentSummary"];
            /** Siblings */
            siblings: components["schemas"]["SegmentSummary"][];
            /** Span */
            span: components["schemas"]["Message"][];
        };
        /**
         * SegmentSummary
         * @description A machine segment as listed in the review queue.
         */
        SegmentSummary: {
            /** Bertopic Subtopic */
            bertopic_subtopic?: string | null;
            /** Bertopic Topic */
            bertopic_topic?: string | null;
            /** Chunk Index */
            chunk_index: number;
            /** Conversation */
            conversation: string;
            /** Id */
            id: number;
            /** Label Confidence */
            label_confidence?: number | null;
            /** Message Indices */
            message_indices: number[];
            /**
             * Reviewed
             * @default false
             */
            reviewed: boolean;
            /** Sentiment */
            sentiment?: string | null;
            /** Subtopic */
            subtopic?: string | null;
            /** Summary */
            summary?: string | null;
            /** Topic */
            topic?: string | null;
            /** True Subtopic */
            true_subtopic?: string | null;
            /** True Topic */
            true_topic?: string | null;
        };
        /**
         * Stats
         * @description Review progress for a dataset.
         *
         *     ``reviewed_match``/``reviewed_mismatch`` compare each reviewed gold segment's
         *     human topic/subtopic (slugs) against its BERTopic source label (slugified) —
         *     a quick agreement signal that drives the mismatch quick-filter.
         */
        Stats: {
            /** Per Topic */
            per_topic?: {
                [key: string]: number;
            };
            /** Reviewed */
            reviewed: number;
            /**
             * Reviewed Match
             * @default 0
             */
            reviewed_match: number;
            /**
             * Reviewed Mismatch
             * @default 0
             */
            reviewed_mismatch: number;
            /** Total */
            total: number;
            /** Unreviewed */
            unreviewed: number;
        };
        /**
         * TaxonomyCreateRequest
         * @description Create a taxonomy option (idempotent on dataset/kind/topic/subtopic).
         */
        TaxonomyCreateRequest: {
            /** Description */
            description?: string | null;
            /**
             * Kind
             * @default user
             */
            kind: string;
            /** Subtopic */
            subtopic?: string | null;
            /** Topic */
            topic: string;
        };
        /**
         * TaxonomyEntry
         * @description One taxonomy (topic, subtopic) row from the metadata provider.
         */
        TaxonomyEntry: {
            /** Description */
            description?: string | null;
            /** Subtopic */
            subtopic?: string | null;
            /** Topic */
            topic?: string | null;
        };
        /**
         * TaxonomyMergeRequest
         * @description Fold ``from_topic`` into ``into_topic`` (labels cascade, dup rows dropped).
         */
        TaxonomyMergeRequest: {
            /** From Topic */
            from_topic: string;
            /** Into Topic */
            into_topic: string;
            /**
             * Kind
             * @default user
             */
            kind: string;
        };
        /**
         * TaxonomyMutationResponse
         * @description Result of a taxonomy create/rename/merge/delete write.
         */
        TaxonomyMutationResponse: {
            /**
             * Cascaded
             * @default 0
             */
            cascaded: number;
            /** Dataset */
            dataset: string;
            /**
             * Deleted
             * @default 0
             */
            deleted: number;
        };
        /**
         * TaxonomyRenameRequest
         * @description Rename a taxonomy option, cascading to applied segment labels.
         *
         *     Topic-level rename leaves ``subtopic``/``new_subtopic`` unset; subtopic-level
         *     rename sets both the matched ``subtopic`` and the ``new_subtopic`` it becomes.
         */
        TaxonomyRenameRequest: {
            /**
             * Kind
             * @default user
             */
            kind: string;
            /** New Subtopic */
            new_subtopic?: string | null;
            /** New Topic */
            new_topic: string;
            /** Subtopic */
            subtopic?: string | null;
            /** Topic */
            topic: string;
        };
        /**
         * UsedTopics
         * @description Distinct topic names already used for a dataset, most-frequent first.
         */
        UsedTopics: {
            /** Topics */
            topics?: string[];
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_auth_config_api_auth_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthConfig"];
                };
            };
        };
    };
    list_datasets_api_datasets_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_bertopic_labels_api_datasets__dataset__bertopic_labels_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                dataset: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BertopicLabels"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_conversations_api_datasets__dataset__conversations_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
                q?: string | null;
                status?: string | null;
                topic?: string | null;
                labeler?: string | null;
                bertopic_topic?: string | null;
                bertopic_subtopic?: string | null;
                mismatch?: boolean;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                dataset: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_conversation_api_datasets__dataset__conversations__conversation__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                dataset: string;
                conversation: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    replace_boundaries_api_datasets__dataset__conversations__conversation__boundaries_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                dataset: string;
                conversation: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BoundaryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoundaryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_labelers_api_datasets__dataset__labelers_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                dataset: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Labelers"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_segments_api_datasets__dataset__segments_get: {
        parameters: {
            query?: {
                status?: string | null;
                topic?: string | null;
                max_confidence?: number | null;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                dataset: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SegmentSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_segment_api_datasets__dataset__segments__segment_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                dataset: string;
                segment_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SegmentDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    annotate_segment_api_datasets__dataset__segments__segment_id__annotate_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                dataset: string;
                segment_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnnotateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnnotateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clear_segment_annotation_api_datasets__dataset__segments__segment_id__annotate_delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                dataset: string;
                segment_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClearAnnotationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_stats_api_datasets__dataset__stats_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                dataset: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Stats"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_taxonomy_api_datasets__dataset__taxonomy_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                dataset: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaxonomyEntry"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_taxonomy_api_datasets__dataset__taxonomy_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                dataset: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaxonomyCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaxonomyMutationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_taxonomy_api_datasets__dataset__taxonomy_delete: {
        parameters: {
            query: {
                topic: string;
                subtopic?: string | null;
                kind?: string;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                dataset: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaxonomyMutationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rename_taxonomy_api_datasets__dataset__taxonomy_patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                dataset: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaxonomyRenameRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaxonomyMutationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    merge_taxonomy_api_datasets__dataset__taxonomy_merge_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                dataset: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaxonomyMergeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaxonomyMutationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_used_topics_api_datasets__dataset__used_topics_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                dataset: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsedTopics"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
